# Server Configuration
server.host=172.20.10.7
server.tcp.port=5050
server.udp.port=5051

# Service Node Port Mappings
service.base64.port=6001
service.compression.port=6002
service.csv.port=6003
service.entropy.port=6004
service.image.port=6005
